/* Generated by restful-react */

import React from "react";
import { Mutate, MutateProps, useMutate, UseMutateProps } from "restful-react";

export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

export interface ModificationSeuilDescription {
  status?: number;
}

export interface PostSeuilsRequestBody {
  seuils?: {
    magasin?: string;
    zone?: string;
    seuil_min?: number;
    seuil_max?: number;
    critere?: "DB_DQLM1" | "DB_DQPM1";
  }[];
}

export type PostSeuilsProps = Omit<
  MutateProps<ModificationSeuilDescription, void, void, PostSeuilsRequestBody>,
  "path" | "verb"
>;

export const PostSeuils = (props: PostSeuilsProps) => (
  <Mutate<ModificationSeuilDescription, void, void, PostSeuilsRequestBody> verb="PUT" path={`/seuils`} {...props} />
);

export type UsePostSeuilsProps = Omit<
  UseMutateProps<ModificationSeuilDescription, void, PostSeuilsRequestBody>,
  "path" | "verb"
>;

export const usePostSeuils = (props: UsePostSeuilsProps) =>
  useMutate<ModificationSeuilDescription, void, void, PostSeuilsRequestBody>("PUT", `/seuils`, props);
